### ISSUE TITLE
Please update or remove peerDependencies markdown-it

### ISSUE THREAD

**Issue by anisabboud** [boyum/markdown-it-image-size#396]
Hi, thank you for the nice plugin! It worked well.

However, I ran into an issue with `npm install markdown-it-image-size`:
```dart
npm ERR! Could not resolve dependency:
npm ERR! peer markdown-it@"^12.0.4" from markdown-it-image-size@0.4.1
npm ERR! node_modules/markdown-it-image-size
npm ERR!   dev markdown-it-image-size@"^0.4.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: markdown-it@12.3.2
npm ERR! node_modules/markdown-it
npm ERR!   peer markdown-it@"^12.0.4" from markdown-it-image-size@0.4.1
npm ERR!   node_modules/markdown-it-image-size
npm ERR!     dev markdown-it-image-size@"^0.4.1" from the root project
```

Basically, markdown-it is up-to-date in `devDependencies`:
https://github.com/boyum/markdown-it-image-size/blob/c04123d0dcdf3181efbcfd9c18b6d40cb67e6e29/package.json#L47

But out of date in `peerDependencies`:
https://github.com/boyum/markdown-it-image-size/blob/c04123d0dcdf3181efbcfd9c18b6d40cb67e6e29/package.json#L56-L58

It seems like the depfu bot isn't updating peerDependencies :)
Can you please update it and release a new version to npm? (or remove peerDependencies if it's not needed)

**Comment by boyum** [comment]
Hi, @anisabboud! Thanks for the feedback! I have published two new versions of the npm package and intend to follow the `markdown-it` version number from now on. `12.0.0` has no changes from before, while `13.0.0` has the proposed changes (if I have typed out the version format correctly). Please update to v13 and see if it works! ✨

**Comment by anisabboud** [comment]
@boyum Thanks a lot for the quick response!!

For some reason the `dist` folder is missing in the new versions (`12.0.0`, `13.0.0`):
![image](https://user-images.githubusercontent.com/5672108/197712725-e855a634-4bb1-4ff6-949f-cb969f3dedd5.png)

The older version had a dist folder with the plugin code :)
![image](https://user-images.githubusercontent.com/5672108/197712714-26b818d9-5638-4c62-acbc-e26bbee8b032.png)

**Comment by boyum** [comment]
`13.0.1` is out @anisabboud
