### ISSUE TITLE
TypeError: consumeBody(...).clone is not a function

### ISSUE THREAD

**Issue by cossssmin** [boyum/markdown-it-image-size#399]
I have this markdown content:

```md
![barley](//images.ctfassets.net/kpzg83k38b4x/7EBkxPB3EDz0wJKRJhEq3q/916f98bd010edc03c87e82e5c1e79a7b/barley.jpg)
```

... and I init `markdown-it` with the plugin like so:

```js
import MarkdownIt from 'markdown-it'
import { markdownItImageSize } from 'markdown-it-image-size'

const md = new MarkdownIt('default', {
  linkify: true,
  breaks: true,
})

md.use(markdownItImageSize)
```

I'm getting this `TypeError`:

```
TypeError: consumeBody(...).clone is not a function
    at SyncResponse.buffer (browser.js:287:30)
    at getImageDimensionsFromExternalImage (index.js:1428:27)
    at md.renderer.rules.image (index.js:1392:15)
    at Renderer.renderInline (renderer.js:275:23)
    at Renderer.render (renderer.js:330:22)
    at MarkdownIt.render (index.js:544:24)
```

Any ideas what might be causing it?

**Comment by boyum** [comment]
Hi! I haven't been able to reproduce this issue yet, but I did see that you used `//` instead of setting the protocol explicitly. This wasn't supported before, so I added it in #400. As that might have been the problem, could you try installing `markdown-it-image-size@next`?

If not, which version of MarkdownIt do you use?

**Comment by cossssmin** [comment]
Hi, thanks for the quick response!

Yeah, it doesn't have a protocol as that's what I'm getting from the API (Contentful in this case). But it made no difference when the protocol was added, forgot to mention.

I've updated to `markdown-it-image-size@next` and am using `markdown-it@13.0.1`, but I'm still getting the error - looks like it's coming from `sync-fetch`:

<img alt="image" src="https://user-images.githubusercontent.com/1656595/200171939-de914532-ff50-456d-ba76-903ccb261200.png">

... which is this method in its `browser.js`:

<img alt="image" src="https://user-images.githubusercontent.com/1656595/200172114-1769ddcc-9b1f-4eda-a849-44eae5360643.png">

By the way, I'm using this in a Nuxt 2 static site, and when I tried building it with the `next` version I also got this error:

```
3:02:59 PM: $ npm run generate
3:02:59 PM: > generate
3:02:59 PM: > nuxt generate
3:03:11 PM: [fatal] Nuxt build error
3:03:11 PM:   ERROR in ./node_modules/markdown-it-image-size/dist/index.js
3:03:11 PM:   Module not found: Error: Can't resolve 'fs' in 'node_modules/markdown-it-image-size/dist'
  @ ./node_modules/markdown-it-image-size/dist/index.js 5:17-30
3:03:11 PM:   @ ./plugins/markdown-it.js
3:03:11 PM:   @ ./node_modules/.cache/nuxt/index.js
3:03:11 PM:   @ ./node_modules/.cache/nuxt/client.js
3:03:11 PM:   @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js
```

For context, this is what I'm doing in `plugins/markdown-it.js`:

```js
import MarkdownIt from 'markdown-it'
import { markdownItImageSize } from 'markdown-it-image-size'

const addLazyAttribute = md => {
  md.renderer.rules.image = function (tokens, idx, options, env, self) {
    const token = tokens[idx]
    const src = token.attrGet('src')
    const alt = md.utils.escapeHtml(token.content)

    return `<img src="${src}" alt="${alt}" loading="lazy">`
  }
}

export default ({}, inject) => {
  const md = new MarkdownIt('default', {
    linkify: true,
    breaks: true,
  })

  md
    .use(addLazyAttribute)
    .use(markdownItImageSize)

  // Make $md available in Nuxt pages
  inject('md', md)
}
```

**Comment by boyum** [comment]
Ahh, I see. Thanks for debugging! It seems that Nuxt runs in a browser context, which the plugin wasn't really made for. To solve this, I see two ways forward: Either make it work in browsers as well, or avoid adding the attributes in browsers. I think the latter option is the best, to avoid overriding the browser's asset queue. As you're using `loading="lazy"`, I assume you'd prefer not to download the images early.

Does this sound like a good way forward? We could add a `window === "undefined"` check before we try to download the images.

For the Nuxt generate error, I've found this which might work https://github.com/nuxt/bridge/issues/253#issuecomment-1098193453.
