### ISSUE TITLE
how to use this plugin?

### ISSUE THREAD

**Issue by jackywu** [boyum/markdown-it-image-size#60]
how to use this plugin? is there a simple manual?

**Comment by boyum** [comment]
Hi! I just added the answer to the readme. To use MarkdownIt plugins, use the `use` method on the MarkdownIt object:

```js
const MarkdownIt = require("markdown-it");
const { markdownItImageSize } = require("markdown-it-image-size");

const mdRenderer = MarkdownIt();
mdRenderer.use(markdownItImageSize);
```

The plugin will add dimensions to any _local_ image rendered by MarkdownIt.
