### ISSUE TITLE
Vitepress support

### ISSUE THREAD

**Issue by khang-nd** [boyum/markdown-it-image-size#761]
Sorry for dropping yet another request, but I can't seem to get the plugin to work with my website that uses Vitepress. Essentially, I had to modify your code to make it work with Vitepress.

I'd gladly contribute back to the repo, but I'm not sure how to. If you can either walk me through the steps to contribute (mostly around how the stack works, demo setup and writing tests) or transfer the changes I made in my version ([link to file](https://github.com/Visnalize/.com/blob/v2/.vitepress/plugins/md-image.ts)), that'd be great.

**Comment by boyum** [comment]
No worries at all! I'd like to have a Vitepress example project in the examples directory. You're more than welcome to create a new project there, similar to the 11ty example. Setting one up should not require any other changes to the monorepo itself.

I'd love to help out by making the changes and by teaching you how you can contribute, but I'm not really sure how best to help out. I think this setup should suffice:

1. Clone this repo
1. Run `npm install` from any directory with a `package.json` file
1. Run `npm run build && npm run test` to run tests (unit tests run on build output, this should be fixed, but that's how it is)

**Comment by boyum** [comment]
I started on #762 if that helps.

**Comment by khang-nd** [comment]
Wonderful, I'll have a crack at it when I get the time.

**Comment by boyum** [comment]
I think the code runs correctly now (at least it does locally), however there are some issues building VitePress in CI which I haven't figured out yet.

**Comment by boyum** [comment]
Fix'd ✨

**Comment by boyum** [comment]
Added to v14.6.0!
